article/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView



urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list_of_articles'),
    path('<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path()
]

saleskg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from saleskg import settings
from . import views
from .views import IndexPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPage.as_view(),name='catalog'),
]   
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:key>/detail/', views.post_detail, name='post_detail'),
    path('<int:key>/update/', views.post_update, name='post_update'),
    path('create/', views.post_create, name='post_create'),
    path('<int:key>/delete', views.post_delete, name='post_delete')
]

article/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class ArticleCategory(models.Model):
    name = models.CharField(verbose_name='Названия категорий', max_length=64, blank=True, null=True)
    
    def __str__(self):
        return self.name

class Article(models.Model):
    name = models.CharField(verbose_name='Название работы', max_length=128, blank=True, null=True)
    text = models.TextField(verbose_name='Описание работы', blank=True, null=True)
    price = models.PositiveIntegerField(verbose_name='Цена', blank=True, null=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=16, blank=True, null=True)
    category = models.ForeignKey(ArticleCategory, on_delete=models.SET_NULL, verbose_name='Категории', blank=True, null=True)


class ArticleImage(models.Model):
    image = models.ImageField(verbose_name='Фотографии', upload_to='articleimage/', blank=True, null=True,)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='Объявление',blank=True, null=True)

article/views.py
from django.shortcuts import render
from .models import Article
from django.views.generic import ListView, DetailView


class ArticleListView(ListView):
    model = Article
    template_name = "article/article_list.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.all()
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = "article/article_detail.html"

saleskg/views.py
from article.models import Article
from django.views.generic import ListView 

class IndexPage(ListView):
    model = Article 
    template_name = 'article/index.html'

templates/article/article_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Галерея</title>

    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">                
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                      
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                  

    
</head>

    <body>
        
        <div class="container">
            <header class="tm-site-header">
                <h1 class="tm-site-name">Закир Калкабаев</h1>
                <p class="tm-site-description">художник-портретист</p>
                
                <nav class="navbar navbar-expand-md tm-main-nav-container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#tmMainNav" aria-controls="tmMainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse tm-main-nav" id="tmMainNav">
                        <ul class="nav nav-fill tm-main-nav-ul">
                            <li class="nav-item"><a class="nav-link" href=>Главное</a></li>
                            <li class="nav-item"><a class="nav-link active" href="preview.html">Каталог</a></li>
                            <li class="nav-item"><a class="nav-link" href="contact.html">Контакты</a></li>
                        </ul>
                    </div>    
                </nav>
                
            </header>
            
            <div class="tm-main-content no-pad-b">
                    
                <section class="row tm-item-preview">
                    <div class="col-md-6 col-sm-12 mb-md-0 mb-5">
                        <h1>{{article.name}}</h1
                        <p>{{article.text}}</p>
                        <p>{{article.price}}</p>
                        <p>{{article.phone}}</p>
                        <p>{{article.image}}</p>
                        <p>{{article.category}}</p>
                            
                        {% for y in article.articleimage_set.all %}
                        <img src={{y.image.url}} alt="Image" class="img-fluid tm-img-center-sm">
                        {% endfor %}
                    </div>
                </section>
             
                            
            </div>

            <footer>
                Авторское право &copy; <span class="tm-current-year">2020</span> принадлежит Закиру Калкабаеву 
                
                - Сайт разработан Бахтияром Закировым
            </footer>    
        </div>
        
        
        <script src="js/jquery-1.11.3.min.js"></script>         
        <script src="js/popper.min.js"></script>                
        <script src="js/bootstrap.min.js"></script>             
        <script>     
       
            $(document).ready(function(){
                
                
                $('.tm-current-year').text(new Date().getFullYear());

            });

        </script>             

</body>
</html>

templates/article/article_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Галерея</title>

    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">                
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                      
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                   

    
</head>

    <body>
        
        <div class="container">
            <header class="tm-site-header">
                <h1 class="tm-site-name">Каталог</h1>
                                
                <nav class="navbar navbar-expand-md tm-main-nav-container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#tmMainNav" aria-controls="tmMainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse tm-main-nav" id="tmMainNav">
                        <ul class="nav nav-fill tm-main-nav-ul">
                            <li class="nav-item"><a class="nav-link" href="index.html">Главное</a></li>
                            <li class="nav-item"><a class="nav-link active" href="preview.html">Каталог</a></li>
                            <li class="nav-item"><a class="nav-link" href="contact.html">Контакты</a></li>
                        </ul>
                    </div>    
                </nav>
                
            </header>
            
            <div class="tm-gallery">
                <div class="row">
                    <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                        <a href="article_detail.html">
                            <div class="tm-gallery-item-overlay">
                                {% for article in article_list%}
                                <a href="{% url 'article_detail' pk=article.pk %}"><h1>{{article.name}}</h1></a>
                                <p class="tm-figcaption"> {{article.image}}</p>
                                <a href="preview.html"></a><p>{{article.category}}</p>

                                {% for y in article.articleimage_set.all %}
                                <img src={{y.image.url}} alt="Image" class="img-fluid tm-img-center">
                                {% endfor %}
                                {% endfor %}
                            </div>
                            
                            <p class="tm-figcaption">Табун</p>
                        </a>
                    </figure>

 
                </div>   
            </div>                   
                            
            </div>

            <footer>
                Авторское право &copy; <span class="tm-current-year">2020</span> принадлежит Закиру Калкабаеву 
                
                - Сайт разработан Бахтияром Закировым
            </footer>    
        </div>
        
        
        <script src="js/jquery-1.11.3.min.js"></script>         
        <script src="js/popper.min.js"></script>                
        <script src="js/bootstrap.min.js"></script>             
        <script>     
       
            $(document).ready(function(){
                
                
                $('.tm-current-year').text(new Date().getFullYear());

            });

        </script>            

</body>
</html>

templates/article/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--

Template 2092 Shelf

http://www.tooplate.com/view/2092-shelf

-->
    <title>Галерея</title>

    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">                <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                      
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                    <!-- Templatemo style -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

    <body>
        
        <div class="container">
            <header class="tm-site-header">
                <h1 class="tm-site-name">Закир Калкабаев</h1>
                <p class="tm-site-description">художник-портретист</p>
                
                <nav class="navbar navbar-expand-md tm-main-nav-container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#tmMainNav" aria-controls="tmMainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse tm-main-nav" id="tmMainNav">
                        <ul class="nav nav-fill tm-main-nav-ul">
                            <li class="nav-item"><a class="nav-link" href="index.html">Главное</a></li>
                            <li class="nav-item"><a class="nav-link" href="preview.html">Каталог</a></li>
                            <li class="nav-item"><a class="nav-link active" href="contact.html">Контакты</a></li>
                        </ul>
                    </div>    
                </nav>
                
            </header>
            
            <div class="tm-main-content">
                <section class="row tm-margin-b-l">
                    <div class="col-12">
                        <h2 class="tm-blue-text tm-margin-b-p">Для заказа</h2>
                    </div>
                    <div class="col-md-6 col-sm-12 mb-md-0 mb-5 tm-overflow-auto">         
                        <div class="mr-lg-5">
                            <!-- contact form -->
                            <form action="#" method="post" class="tm-contact-form">
                                <div class="form-group">
                                    <input type="text" id="contact_name" name="contact_name" class="form-control" placeholder="Ваше имя"  required/>
                                </div>
                                <div class="form-group">                                                        
                                    <input type="email" id="contact_email" name="contact_email" class="form-control" placeholder="Ваш Email"  required/>
                                </div>
                                <div class="form-group">
                                    <textarea id="contact_message" name="contact_message" class="form-control" rows="8" placeholder="Ваше сообщение" required></textarea>
                                </div>
                                <button type="submit" class="tm-btn tm-btn-blue float-right">ОТПРАВИТЬ</button>
                            </form>                          
                        </div>                                       
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <p class="tm-margin-b-p">Для заказа портретов и картин и покупки готовых работ,обращайтесь по следующим контактам:</p>
                        <address>
                            
                            <div class="tm-blue-text">          
                                Email: <a class="tm-blue-text" href="mailto:zabaxa90@gmail.com">zabaxa90@gmail.com</a
                                ><br>
                                Тел.: <a class="tm-blue-text" href="tel:+996558333501">0 558 333 501; </a><a class="tm-blue-text" href="tel:+996502333501">0 502 333 501</a><br>
                                <a href="https://www.instagram.com/zakirkalkabaev/">Instagram: zakirkalkabaev   </a>         
                            </div>                            
                        </address>
                        
                    </div>
                </section>

                <section class="row tm-margin-b-l">
                    <div class="col-12">
                        <header>
                            <h4 class="tm-blue-text tm-margin-b">Наш адрес</h4>
                        </header>
                        <div id="google-map"></div>
                    </div>
                </section>
            </div>

            <footer>
                Авторское право &copy; <span class="tm-current-year">2020</span> принадлежит Закиру Калкабаеву 
                
                - Сайт разработан Бахтияром Закировым
            </footer>    
        </div>
        
        
        <script src="js/jquery-1.11.3.min.js"></script>         
        <script src="js/popper.min.js"></script>                
        <script src="js/bootstrap.min.js"></script>             
        <script>     

            
            var map = '';
            var center;

            function initialize() {
                var mapOptions = {
                    zoom: 16,
                    center: new google.maps.LatLng(37.769725, -122.462154),
                    scrollwheel: false
                };
            
                map = new google.maps.Map(document.getElementById('google-map'),  mapOptions);

                google.maps.event.addDomListener(map, 'idle', function() {
                  calculateCenter();
                });
            
                google.maps.event.addDomListener(window, 'resize', function() {
                  map.setCenter(center);
                });
            }

            function calculateCenter() {
                center = map.getCenter();
            }

            
            function loadGoogleMap(){
                var script = document.createElement('script');
                script.type = 'text/javascript';
				// use your own API key for Google Maps
                script.src = 'https://maps.googleapis.com/maps/api/js?key=AIzaSyC_iLYB-9nzlBfwB18WEDTCMla3Cr97lsg&v=3.exp&sensor=false&' + 'callback=initialize';
                document.body.appendChild(script);
            } 
       
            $(document).ready(function(){

                // Google Map
                loadGoogleMap();  
                
                // Update the current year in copyright
                $('.tm-current-year').text(new Date().getFullYear());

            });

        </script>             

</body>
</html>

templates/article/details.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Галерея</title>

    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">                
    <link rel="stylesheet" href="css/bootstrap.min.css">                                      
    <link rel="stylesheet" href="css/tooplate-style.css">                                   

    
</head>

    <body>
        
        <div class="container">
            <header class="tm-site-header">
                <h1 class="tm-site-name">Закир Калкабаев</h1>
                <p class="tm-site-description">художник-портретист</p>
                
                <nav class="navbar navbar-expand-md tm-main-nav-container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#tmMainNav" aria-controls="tmMainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse tm-main-nav" id="tmMainNav">
                        <ul class="nav nav-fill tm-main-nav-ul">
                            <li class="nav-item"><a class="nav-link" href="index.html">Главное</a></li>
                            <li class="nav-item"><a class="nav-link active" href="preview.html">Каталог</a></li>
                            <li class="nav-item"><a class="nav-link" href="contact.html">Контакты</a></li>
                        </ul>
                    </div>    
                </nav>
                
            </header>
            
            <div class="tm-main-content no-pad-b">
                    
                <section class="row tm-item-preview">
                    <div class="col-md-6 col-sm-12 mb-md-0 mb-5">
                        <img src="img2/image-09.jpg" alt="Image" class="img-fluid tm-img-center-sm">
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <h2 class="tm-blue-text tm-margin-b-p">Байтик Баатыр</h2>
                        <p class="tm-margin-b-p">Цветной портрет маслянными красками на холсте.</p>
                        <p class="tm-margin-b-p">Для заказа данной работы или любой другой просим обращаться по нашим <a href="contact.html">контактам.</a></p>
                        
                        
                    </div>
                </section>
             
                            
            </div>

            <footer>
                Авторское право &copy; <span class="tm-current-year">2020</span> принадлежит Закиру Калкабаеву 
                
                - Сайт разработан Бахтияром Закировым
            </footer>    
        </div>
        
        
        <script src="js/jquery-1.11.3.min.js"></script>         
        <script src="js/popper.min.js"></script>                
        <script src="js/bootstrap.min.js"></script>             
        <script>     
       
            $(document).ready(function(){
                
                
                $('.tm-current-year').text(new Date().getFullYear());

            });

        </script>             

</body>
</html>

templates/article/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Галерея</title>

    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  
    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">                
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                      
    <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                   

    
</head>

    <body>
        
        <div class="container">
            <header class="tm-site-header">
                <h1 class="tm-site-name">Закир Калкабаев</h1>
                <p class="tm-site-description">художник-портретист</p>
                
                <nav class="navbar navbar-expand-md tm-main-nav-container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#tmMainNav" aria-controls="tmMainNav" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse tm-main-nav" id="tmMainNav">
                        <ul class="nav nav-fill tm-main-nav-ul">
                            <li class="nav-item"><a class="nav-link" href="index.html">Главное</a></li>
                            <li class="nav-item"><a class="nav-link" href="preview.html">Каталог</a></li>
                            <li class="nav-item"><a class="nav-link active" href="contact.html">Контакты</a></li>
                        </ul>
                    </div>
                </nav>
                
            </header>
            
            <div class="tm-main-content">
                <section class="tm-margin-b-l">
                    <header>
                        <h2 class="tm-main-title">Добро пожаловать в нашу галерею</h2>    
                    </header>
                    
                    <p>Рады приветствовать Вас в нашем сайте! Здесь Вы можете ознакомиться с некоторыми работами кыргызского художника с 30-летним стажем, а также сделать заказ потретов, шаржей и картин на любой вкус.</p>
                    
                    <div class="tm-gallery">
                        <div class="row">
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-01.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    
                                    <p class="tm-figcaption">Копия работы голландского художника Франса Халса "Компания капитана Рейнера"</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-02.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Скачки</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-07.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Натюрморт</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-08.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Лошади</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-05.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Шаржи одиночные</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-06.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Парные шаржи</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{%  static 'img2/image-13.jpg'  %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Цветные потреты на заказ</p>
                                </a>
                            </figure>
                            <figure class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
                                <a href="preview.html">
                                    <div class="tm-gallery-item-overlay">
                                        <img src="{% static 'img2/image-03.jpg' %}" alt="Image" class="img-fluid tm-img-center">
                                    </div>
                                    <p class="tm-figcaption">Чёрно-белые потреты на заказ</p>
                                </a>
                            </figure> 
                        </div>   
                    </div>
                    
                    <nav class="tm-gallery-nav">
                        <ul class="nav justify-content-center">
                            <li class="nav-item"><a class="nav-link active" href="preview.html">Смотреть больше</a></li>
                        </ul>
                    </nav>
                </section>

                </div>

            <footer>
                Авторское право &copy; <span class="tm-current-year">2020</span> принадлежит Закиру Калкабаеву 
                
                - Сайт разработан Бахтияром Закировым
            </footer>    
        </div>
        
        
        <script src="js/jquery-1.11.3.min.js"></script>         
        <script src="js/popper.min.js"></script>                
        <script src="js/bootstrap.min.js"></script>             
        <script>     
       
            $(document).ready(function(){
                
                
                $('.tm-current-year').text(new Date().getFullYear());

            });

        </script>             

</body>
</html>